# Initial Clustering

```{r}
load("./data/dtms.Rdata")
```

### Cosine Distance Function
```{r}
# cosine distance / similarity calc as DAM block session 5

cosineSim <- function(x){
  as.dist(x%*%t(x)/(sqrt(rowSums(x^2) %*% t(rowSums(x^2)))))
}

# add distance function

cosineDist <- function(x){
  x <- cosineSim(x)
  x <- 1-x
}
```


## Heirachical

### Preprocessed first dtm
```{r}
#convert document term matrix to matrix
p_mat <- as.matrix(p_dtm)

# calc euclidian distance
p_dist <- dist(p_mat)

p_groups <- hclust(p_dist,method="ward.D")
plot(p_groups, hang=-1)

p_cosine_dist <- cosineDist(p_mat)

p_cd_groups <- hclust(p_cosine_dist,method="ward.D")
#plot, use hang to ensure that labels fall below tree
plot(p_cd_groups, hang=-1)
#cut into ?? subtrees. need to tweak

rectc <- rect.hclust(p_cd_groups,2)
p_hclusters_cosine <- cutree(p_cd_groups,2)
```


## K-Means

### Initial DTM
```{r}
p_kfit <- kmeans(p_cosine_dist, 2, nstart=100)

clusplot(as.matrix(p_cosine_dist), p_kfit$cluster, color=T, shade=T, labels=2, lines=0)

withinsumsquares <- 2:(nrow(p_mat)-1)
for (i in 2:(nrow(p_mat)-1)) withinsumsquares[i] <- sum(kmeans(p_cosine_dist,centers=i,nstart=25)$withinss)
plot(2:(nrow(p_mat)-1), withinsumsquares[2:(nrow(p_mat)-1)], type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares") 

# no elbow?? 5?

p_kfit <- kmeans(p_cosine_dist, 5, nstart=100)

clusplot(as.matrix(p_cosine_dist), p_kfit$cluster, color=T, shade=T, labels=2, lines=0)

# visual 10??

p_kfit <- kmeans(p_cosine_dist, 10, nstart=100)

clusplot(as.matrix(p_cosine_dist), p_kfit$cluster, color=T, shade=T, labels=2, lines=0)

# how do i find what is important in similarity???

```

## Refined DTM
```{r}
f_mat <- as.matrix(dtmf)

f_cosine_dist <- cosineDist(f_mat)

f_cd_groups <- hclust(f_cosine_dist,method="ward.D")

plot(f_cd_groups, hang=-1)

f_kfit <- kmeans(f_cosine_dist, 10, nstart=100)

clusplot(as.matrix(f_cosine_dist), f_kfit$cluster, color=T, shade=T, labels=2, lines=0)

```

### tfidf
```{r}
tfidf_mat <- as.matrix(dtm_tfidf)

tfidf_cosine_dist <- cosineDist(tfidf_mat)

tfidf_cd_groups <- hclust(tfidf_cosine_dist,method="ward.D")

plot(tfidf_cd_groups, hang=-1)

tfidf_kfit <- kmeans(tfidf_cosine_dist, 10, nstart=100)

clusplot(as.matrix(tfidf_cosine_dist), tfidf_kfit$cluster, color=T, shade=T, labels=2, lines=0)

tfidf_sil <- silhouette(tfidf_kfit$cluster, tfidf_cosine_dist)
plot(tfidf_sil)
```

```{r}
# https://uc-r.github.io/kmeans_clustering#silo

# function to compute average silhouette for k clusters
avg_sil <- function(k) {
  km.res <- kmeans(tfidf_cosine_dist, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, stats::dist(tfidf_cosine_dist))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- 2:40

# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)

plot(k.values, avg_sil_values,
       type = "b", pch = 19, frame = FALSE, 
       xlab = "Number of clusters K",
       ylab = "Average Silhouettes",
       main = "TFIDF Clustering")

# 2 or 5 for tfidf not substantial <0.2
```

```{r}
tfidf_kfit2 <- kmeans(tfidf_cosine_dist, 2, nstart=100)
tfidf_kfit5 <- kmeans(tfidf_cosine_dist, 5, nstart=100)

clusplot(as.matrix(tfidf_cosine_dist), tfidf_kfit5$cluster, color=T, shade=T, labels=2, lines=0)

tfidf_kfit2_clusters <- as.data.frame(tfidf_kfit2$cluster) %>% 
  rownames_to_column() %>% 
  remove_rownames()

tfidf_kfit5_clusters <- as.data.frame(tfidf_kfit5$cluster) %>% 
  rownames_to_column() %>% 
  remove_rownames()

initial_clusters <- merge(tfidf_kfit2_clusters, tfidf_kfit5_clusters, by = "rowname")
```

```{r}
# https://uc-r.github.io/kmeans_clustering#silo

# function to compute average silhouette for k clusters
avg_sil <- function(k) {
  km.res <- kmeans(f_cosine_dist, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, stats::dist(f_cosine_dist))
  mean(ss[, 3])
}

# Compute and plot wss for k = 2 to k = 15
k.values <- 2:40

# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)

plot(k.values, avg_sil_values,
       type = "b", pch = 19, frame = FALSE, 
       xlab = "Number of clusters K",
       ylab = "Average Silhouettes",
     main = "Refined Wordlist Clusters")


#3 or 5 for f_cosine >0.3 weak
```

```{r}
f_kfit3 <- kmeans(f_cosine_dist, 3, nstart=100)

clusplot(as.matrix(f_cosine_dist), f_kfit3$cluster, color=T, shade=T, labels=2, lines=0)

f_kfit3_clusters <- as.data.frame(f_kfit3$cluster) %>% 
  rownames_to_column() %>% 
  remove_rownames()

initial_clusters <- merge(initial_clusters, f_kfit3_clusters, by = "rowname")
```

# Network Graph

```{r}
#convert dtm to matrix (what format is the dtm stored in?)
tfidf_mat <- as.matrix(dtm_tfidf)

#Map filenames to matrix row numbers
#these numbers will be used to reference files in the network graph
filekey <- cbind(1:42,rownames(tfidf_mat))

rownames(tfidf_mat) <- 1:42
#compute cosine similarity between document vectors
#converting to distance matrix sets diagonal elements to 0
cs <- cosineSim(tfidf_mat)

#adjacency matrix: set entries below a certain threshold to 0.
#We choose half the magnitude of the largest element of the matrix
#as the cutoff. This is an arbitrary choice
cs[cs < mean(cs)] <- 0
cs <- round(cs,3)
#write to disk

# build a graph from the above matrix
#mode is undirected because similarity is a bidirectional relationship
g <- graph.adjacency(as.matrix(cs), weighted=T, mode = "undirected")

#Plot a Graph
# Another graphing library you might consider is visNetwork, which allows you to interact with the graph
# http://datastorm-open.github.io/visNetwork/
# set seed to make the layout reproducible
set.seed(42)
#one of many possible layouts, see igraph docs
layout1 <- layout.fruchterman.reingold(g)
#basic plot with no weighting - fruchtermann reingold weighting
plot(g, layout=layout1)
#another layout
plot(g, layout=layout.kamada.kawai)

#Community detection - Fast/Greedy
comm_fg <- fastgreedy.community(g)
comm_fg$membership
V(g)$color <- comm_fg$membership
plot(g, layout=layout.kamada.kawai)
community_mapping_init <- cbind(as.data.frame(filekey, row.names = F),comm_fg$membership)


# found 4 communities as did sillohette

#Community detection - Louvain
comm_lv <- cluster_louvain(g)
comm_lv$membership
V(g)$color <- comm_lv$membership
plot(g, layout=layout.kamada.kawai)
community_mapping_init <- cbind(community_mapping_init,comm_lv$membership)


#Community detection - spinglass
comm_sg <- cluster_spinglass(g)
comm_sg$membership
V(g)$color <- comm_sg$membership
plot(g, layout=layout.kamada.kawai)
community_mapping_init <- cbind(community_mapping_init,comm_sg$membership)

#all have same grouping

initial_clusters$networkmapgroups <- community_mapping_init$`comm_fg$membership`

#lets weight the nodes and edges
#set label (not really necessary)
#V=vertex, E=edge
V(g)$label <- V(g)$name
#Vertex size proportional to number of connections
V(g)$size <- degree(g)*.6
#Vertex label size proportional to number of connections
V(g)$label.cex <-  degree(g) / max(degree(g))+ .8
#label colour default black
V(g)$label.color <- "black"
#Vertex color organe
V(g)$color <- "orange"
#edge color grey
E(g)$color <- "grey"
#edge width proportional to similarity (weight)
E(g)$width <- E(g)$weight*7
# plot the graph in layout1 (fruchtermann reingold)
plot(g, layout=layout1)
#output is quite ugly. Explore igraph to see how you
#can fix it
```

```{r}
#saveRDS(initial_clusters, file = "./data/initial_clusters.RDS")
```

# pretty network
```{r}
g <- graph.adjacency(as.matrix(cs), weighted=T, mode = "undirected")
set.seed(42)

comm_fg <- fastgreedy.community(g)
V(g)$color <- comm_fg$membership

plot(g, layout=layout.kamada.kawai,
     main = "TFIDF Network",
     vertex.color = c("#ff00f9", "#f08025", "#ffffff", "#41cd61"),
     vertex.frame.color= c("#ff00f9", "#f08025", "#ffffff", "#41cd61"),
     vertex.label.color = "black",
     vertex.size = 30,
     edge.curved = TRUE)

```

