# Doc Details

## Crawling post tags and categories

```{r}
library(rvest)
dsrch <- readRDS(file = "./data/dsrch.RDS")
d_urls <- dsrch$url

outframe <- data.frame(url = NA, type = NA, value = NA)[-1,]
catlistframe <- data.frame(url = NA, cats = NA)[-1,]

for (website in d_urls) {
  website_url <- gsub("'", "%E2%80%99", website)
  page <- read_html(URLencode(website_url))
  
  categories <- page %>% 
  html_nodes('a[rel="category tag"]') %>% 
  html_text()
  
  tags <- page %>% 
  html_nodes('a[rel="tag"]') %>% 
  html_text()
  
  catframe <- data.frame(url = website, type = "category", value = categories, stringsAsFactors = FALSE)
  catlist <- paste(categories, collapse = ", ")
  catlist <- data.frame(url = website, cats = catlist, stringsAsFactors = FALSE)
  
  if (length(tags) != 0) {
    tagframe <- data.frame(url = website, type = "tag", value = tags, stringsAsFactors = FALSE)
    catframe <- rbind(catframe, tagframe)
  }
  
  outframe <- rbind(outframe, catframe)
  catlistframe <- rbind(catlistframe, catlist)
}

str(outframe)

tags <- outframe %>% 
  dplyr::filter(type == "tag")

length(unique(tags$page))
# only 9 results have tags, and only a few total

categories <- outframe %>% 
 dplyr::filter(type == "category") %>% 
  select(-type) %>% 
  left_join(dsrch, by = "url")

categories_bin <- categories %>% 
  select(doc, value)


length(unique(categories$value))

categories_bin <- dcast(melt(categories_bin, id.vars="doc", factorsAsStrings=TRUE), doc ~ value, drop=FALSE , fun.aggregate = length, fill = 0)
```


```{r}
cb_blog <- categories_bin %>% 
  gather(x, value, 2:41) %>% 
  mutate(x = factor(x), # alphabetical order by default
         y = factor(doc, levels = rev(unique(doc)))) # force reverse alphabetical order

ggplot(cb_blog, aes(x = x, y = y, fill = value*100)) + geom_tile() + theme_classic() + guides(fill=F) + scale_fill_gradient(low="white", high="#41cd61") + xlab("Topic") + ylab("Document") + ggtitle("Category Tags") + theme(axis.text.x = element_text(angle =50, hjust = 1))
```

40 topics, however, artles fall into multiple topics, how to capture this?

rethink the use of topic models, not just single assignments.

```{r}
# test simiarltiy with 40 topic model?

catass <- categories %>% 
  select(doc, value)
catass$doc <- as.factor(catass$doc)
catass$value <- as.factor(catass$value)

catass$doc <- as.numeric(catass$doc)

ftp49ass <- topic49assign %>% 
  select(topicnum, rowname)

howclose <- proxy::dist(cluo, method = NMI, pairwise = TRUE, by_rows = FALSE)

topic_print <- merge(ftp49ass, topicnames49, by = "topicnum")
topic_print <- topic_print %>% 
  arrange(rowname)



```



